itugnu/urls.py
# This file is part of ITUGnu Website, licensed under GNU GPLv3.
# Copyright: ITUGnu <info@itugnu.org>.
# Author: Emin Mastizada <emin@linux.com>
# Author: Ahmed Ihsan Erdem <ihsan@itugnu.org>

from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import logout, password_reset, password_reset_confirm, password_reset_complete
from django.conf.urls.static import static
from django.urls import path, include
from web import views


urlpatterns = [
    path('contact/', views.contact, name='ajax-contact'),
    path('lecture/register/', views.lectures_register, name='lecture-register'),
    path('logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('registration/', views.registration, name='registration'),
    # Login
    path('login/reset/done/', views.password_reset_done, name='password-reset-done'),
    path('login/reset/complete/', password_reset_complete,
         {'template_name': 'auth/password-reset-complete.html'},
         name='password_reset_complete'),
    path('login/reset/<uidb64>/<token>/',
         password_reset_confirm,
         {'template_name': 'auth/password-reset-confirm.html'},
         name='password_reset_confirm'),
    path('login/reset/', password_reset,
         {
            'template_name': 'auth/password-reset.html',
            'email_template_name': 'auth/password-reset-email.html',
            'post_reset_redirect': 'password-reset-done',
         }, name='password-reset'),
    path('login/', views.login_view, name='login'),
    # Lectures
    path('lectures/', views.lectures_list, name='lectures-index'),
    path('faq/', views.faq, name='faq'),
    path('oyz/', views.oyz, name='oyz'),
    path('blog/', include('pinax.blog.urls', namespace='pinax_blog')),
    path('', views.index, name='index'),
) + urlpatterns

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    import debug_toolbar  # pragma: no cover
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns  # pragma: no cover

lecture/models.py
# This file is part of ITUGnu Website, licensed under GNU GPLv3.
# Copyright: ITUGnu <info@itugnu.org>.
# Author: Emin Mastizada <emin@linux.com>

from django.utils.translation import ugettext_lazy as _
from django.db import models
from datetime import timedelta
from common.models import User
from typing import Union
from os import path as ospath
import logging


logger = logging.getLogger(__name__)


def poster_upload_path(instance, filename):
    logger.debug("Uploading file {name} as {lecture} lecture poster".format(
        name=filename, lecture=instance.name
    ))
    return ospath.join('lectures', str(instance.pk), filename)


class Lecture(models.Model):
    name = models.CharField(_("Lecture Name"), max_length=255, blank=False, null=False)
    description = models.TextField(_("Description"), blank=True, null=True)
    poster = models.ImageField(_("Poster"), upload_to=poster_upload_path, blank=True, null=True)
    lecturer = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, related_name='lectures', verbose_name=_("Lecturer")
    )
    classroom = models.CharField(_("Classroom"), max_length=255, blank=True, null=True)
    start_date = models.DateField(_("Start Date"), blank=True, null=True)
    end_date = models.DateField(_("End Date"), blank=True, null=True)
    is_registration_open = models.BooleanField(_("Open for Registration"), default=False)
    external_registration_url = models.URLField(_("External Registration URL"), blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def weeks(self) -> int:
        return int((self.end_date - self.start_date).days / 7)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Lecture')
        verbose_name_plural = _('Lectures')
        ordering = ('created_at',)


class LectureSchedule(models.Model):
    DAYS_OF_WEEK = [
        (1, _("Monday")),
        (2, _("Tuesday")),
        (3, _("Wednesday")),
        (4, _("Thursday")),
        (5, _("Friday")),
        (6, _("Saturday")),
        (7, _("Sunday"))
    ]
    lecture = models.ForeignKey(
        Lecture, on_delete=models.CASCADE, related_name='schedules', verbose_name=_("Lecture")
    )
    start_time = models.TimeField(_("Start Time"))
    end_time = models.TimeField(_("End Time"))
    day_of_week = models.IntegerField(choices=DAYS_OF_WEEK, default=1)

    @property
    def length(self) -> Union[int, float]:
        diff = (
                       timedelta(hours=self.end_time.hour, minutes=self.end_time.minute) -
                       timedelta(hours=self.start_time.hour, minutes=self.start_time.minute)
               ).seconds / 60 / 60
        if diff % 1 == 0.0:
            return int(diff)
        return round(diff, 1)

    def __str__(self):
        return self.lecture.name

    class Meta:
        verbose_name = _('Lecture Schedule')
        verbose_name_plural = _('Lecture Schedules')
        ordering = ('day_of_week', 'start_time',)


class LectureApplication(models.Model):
    lecture = models.ForeignKey(
        Lecture, on_delete=models.CASCADE, related_name='applicants', verbose_name=_("Lecture")
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='applications', verbose_name=_("User")
    )
    is_approved = models.BooleanField(_("Approved"), default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Application for {lecture} from {user}".format(
            lecture=self.lecture.name, user=self.user
        )

    class Meta:
        verbose_name = _('Lecture Application')
        verbose_name_plural = _('Lecture Applications')
        ordering = ('lecture', 'created_at',)

web/templates/lectures/index.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %}{% trans "Lectures" %}{% endblock %}

{% block extra-nav-classes %} nav-dark-default{% endblock %}

{% block content %}
<section class="bg-light" id="lectures">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading text-uppercase">{% trans "Lectures" %}</h2>
                <form action="" method="get">
                    <h3 class="section-subheading text-muted filter-form">
                        {{ lectures.form }}
                        <button type="submit" class="btn btn-dark">{% trans "Filter" %}</button>
                    </h3>
                </form>
            </div>
        </div>
        <div class="row">
            {% if lectures %}
            {% for lecture in lectures.qs %}
            <div class="col-md-4 col-sm-6 lecture-item">
                <a class="lecture-link" data-toggle="modal" href="#lectureModal{{ lecture.pk }}">
                  <div class="lecture-hover">
                    <div class="lecture-hover-content">
                      <i class="fa fa-plus fa-3x"></i>
                    </div>
                  </div>
                  {% if lecture.poster %}
                    <img class="img-fluid" src="{{ lecture.poster.url }}" alt="{{ lecture.name }}">
                  {% else %}
                    <img class="img-fluid" src="{% static "img/lecture/poster.png" %}" alt="{{ lecture.name }}">
                  {% endif %}
                </a>
                <div class="portfolio-caption">
                  <h4>
                    {% if lecture.is_registration_open %}
                      <i class="fa fa-star" title="{% trans "Open for Registration" %}"></i>
                    {% else %}
                      <i class="fa fa-exclamation-circle" title="{% trans "Registration Closed" %}"></i>
                    {% endif %} {{ lecture.name }}
                  </h4>
                  <p class="text-muted">{{ lecture.start_date }} - {{ lecture.end_date }}</p>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="col-md-12 col-sm-12 lecture-item">
                <div class="caption text-center">
                    <h3>{% trans "There is no any lectures, subscribe to get new announcements." %}</h3>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}
{% block contentmodals %}
{% for lecture in lectures.qs %}
<div class="lecture-modal modal fade" id="lectureModal{{ lecture.pk }}" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="close-modal" data-dismiss="modal">
        <div class="lr">
          <div class="rl"></div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <div class="modal-body">
              <!-- Project Details Go Here -->
              <h2 class="text-uppercase">{{ lecture.name }}</h2>
              <pre><p class="item-intro text-muted">{{ lecture.description }}</p></pre>
              <ul class="list-inline">
                <li>
                  <i class="fa fa-calendar" title="{% trans "Dates" %}"></i> {% blocktrans with start=lecture.start_date end=lecture.end_date weeks=lecture.weeks %}{{ start }} - {{ end }} ({{ weeks }} weeks){% endblocktrans %}
                  <ul>
                    {% if lecture.schedules.count %}
                    {% for schedule in lecture.schedules.all %}
                      <li>
                        {{ schedule.get_day_of_week_display }}, {{ schedule.start_time }} - {{ schedule.end_time }}
                      </li>
                    {% endfor %}
                    {% else %}
                    <li>{% trans "Schedule is not announced" %}</li>
                    {% endif %}
                  </ul>
                </li>
                <li>&nbsp;</li>
                <li>
                  <i class="fa fa-map-marker" title="{% trans "Classroom" %}"></i> {% if lecture.classroom %}{{ lecture.classroom }}{% else %}{% trans "Not Announced" %}{% endif %}
                </li>
                <li>
                  <i class="fa fa-user-secret" title="{% trans "Lecturer" %}"></i> {% if lecture.lecturer %}{{ lecture.lecturer }}{% else %}{% trans "Not Announced" %}{% endif %}
                </li>
              </ul>
              {% if lecture.is_registration_open %}
              <div id="enroll-result{{ lecture.pk }}"></div>
              <button class="btn btn-success lecture-register-button" type="button" href="" data-lecture="{{ lecture.pk }}" data-result-box="#enroll-result{{ lecture.pk }}">
                <i class="fa fa-sign-in"></i> {% trans "Enroll" %}
              </button>
              {% else %}
              <button class="btn btn-danger disabled" type="button" href="#" disabled>
                <i class="fa fa-exclamation-circle"></i> {% trans "Registration Closed" %}
              </button>
              {% endif %}
              <button class="btn btn-primary" data-dismiss="modal" type="button">
                <i class="fa fa-times"></i> {% trans "Close" %}</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock %}
{% block footerclass %}bg-dark{% endblock %}